USE Firma
GO

ALTER TABLE ANGAJATI
	ADD CONSTRAINT FK_ANGAJATI_FUNCTII FOREIGN KEY(IdFunctie)
		REFERENCES FUNCTII(IdFunctie)
GO

ALTER TABLE ANGAJATI
	ADD CONSTRAINT FK_ANGAJATI_DEPT FOREIGN KEY(IdDept)
		REFERENCES DEPARTAMENTE(IdDept)
GO

ALTER TABLE VANZARI
	ADD CONSTRAINT FK_VANZARI_ANGAJATI FOREIGN KEY(IdVanzator)
		REFERENCES ANGAJATI(IdAngajat)
GO

ALTER TABLE VANZARI
	ADD CONSTRAINT FK_VANZARI_PRODUSE FOREIGN KEY(IdProdus)
		REFERENCES PRODUSE(IdProdus)
GO

ALTER TABLE VANZARI
	ADD CONSTRAINT FK_VANZARI_CLIENTI FOREIGN KEY(IdClient)
		REFERENCES CLIENTI(IdClient)
GO

ALTER TABLE PRODUSE
	ADD CONSTRAINT FK_PRODUSE_CATEGORII FOREIGN KEY(IdCateg)
		REFERENCES CATEGORII_PROD(IdCateg)
GO